name: CI Self Hosted

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [osx-arm64, win-64]
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies on macOS
      if: matrix.os == 'osx-arm64'
      run: |
        echo "No dependencies to install on macOS."

    - name: Install dependencies on Windows
      if: matrix.os == 'win-64'
      run: |
        echo "No dependencies to install on Windows."

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pytest

    - name: Verify dependencies
      run: |
        pip list

    - name: Run Tests
      run: |
        pytest -v
