# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [macos-latest, windows-latest]
        python-version: ["3.11", "3.12"]
        # python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    # - name: Cache pip
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-

    # Install system dependencies for Ubuntu
    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1 libglib2.0-0 libsm6 libxrender1 libxext6

    # For macOS, ensure necessary dependencies are installed
    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install qt

    # For Windows, ensure necessary dependencies are installed
    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install qt --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pytest

    - name: Verify dependencies
      run: |
        pip list

    - name: Run Tests
      run: |
        pytest
