name: Create Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install -e .

      - name: Build with PyInstaller
        run: |
          pyinstaller HELIUM.spec --clean -y

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Ubuntu Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-ubuntu-latest
          path: dist/ubuntu

      - name: Download macOS Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-macos-latest
          path: dist/macos

      - name: Download Windows Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-windows-latest
          path: dist/windows

      - name: Compress macOS Build Artifact
        run: |
          cd dist/macos
          zip -r HELIUM-macos.zip HELIUM.app

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset - Ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/ubuntu/HELIUM
          asset_name: HELIUM-linux
          asset_content_type: application/octet-stream

      - name: Upload Release Asset - macOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/macos/HELIUM-macos.zip
          asset_name: HELIUM-macos.zip
          asset_content_type: application/zip

      - name: Upload Release Asset - Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/windows/HELIUM.exe
          asset_name: HELIUM-windows.exe
          asset_content_type: application/octet-stream